language: rust
os: linux

script:
  - cargo build --all --features=tools
  - cargo test --all --features=tools

deploy:
  provider: script
  script: ${TRAVIS_BUILD_DIR}/deploy.sh publish
  on:
    condition: '"$(${TRAVIS_BUILD_DIR}/deploy.sh check; echo $?)" -ne 0'
